### ISSUE TITLE
ModuleNotFoundError: No module named 'convert_excel2QA'

### ISSUE THREAD

**Issue by ysnt27** [dasadc/adc2019#24]
In this commit,  
https://github.com/dasadc/adc2019/commit/7e764a32788e89855ab9b4276c41e482e9333048

API server won't start by `adc2019/scripts/04_server.sh`, running `main.py` via `guniconrn main:app`

```
  File "/home/adc/adc2019/server/main.py", line 26, in <module>
    from convert_excel2QA import genA_from_b64
ModuleNotFoundError: No module named 'convert_excel2QA'
```

**Comment by shibasay** [comment]
Finally I concluded the functionality related to this bug is no use. So workaround at 
274a701  (disable it) is reasonable and I close this issue.
